In [1]:
x = 25
x

25

In [2]:
type(x)

int

In [3]:
y = 3


In [4]:
pysum = x+y
pysum

28

In [5]:
type(pysum)

int

In [6]:
xfloat = 25.0
fsum = xfloat + y
type(fsum)

float

# Pytorch
- pytorch tensors are to be pytonic -- behave like numpy arrays
- are easier for operations on GPU
- for automatic differenciation

In [1]:
import torch


In [8]:
xpt = torch.tensor(25)
xpt

tensor(25)

In [10]:
print(xpt.dtype)
print(xpt.shape)

torch.int64
torch.Size([])


# Scalars in Tensorflow
- tensors created with wrapper
- tf.Variable
- tf.constant
- tf.placeholder
- tf.SparseTensor

-- easity convert to and fromm numpy arrays

In [2]:
import tensorflow as tf
print(tf.__version__)



2.16.1


In [4]:
xtf = tf.Variable(23,dtype=tf.int16)
xtf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=23>

In [5]:
xtf.shape

TensorShape([])

In [6]:
ytf = tf.Variable(3,dtype=tf.int16)
ytf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [8]:
sumi = xtf + ytf
sumtf = tf.add(xtf,ytf)
print(sumi)
print(sumtf)

tf.Tensor(26, shape=(), dtype=int16)
tf.Tensor(26, shape=(), dtype=int16)


In [11]:
sumtf.numpy()
sumtf

<tf.Tensor: shape=(), dtype=int16, numpy=26>

In [12]:
tffloat = tf.Variable(25,dtype=tf.float16)
tffloat

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

### High  Rank Tensors
As an example rank 4 tensors are common for images , where each dimensional corresponds to:
1. No of images in pixels e.g for MNIST digits
2.Image width in pixecls e.g. 28
3. Number of color chanels e.g. Full color images

In [2]:
images_pt = torch.rand([32,28,28,3])

In [3]:
images_pt

tensor([[[[0.5815, 0.9191, 0.8477],
          [0.9408, 0.5422, 0.5567],
          [0.7351, 0.5674, 0.8902],
          ...,
          [0.1871, 0.9798, 0.0597],
          [0.1681, 0.9563, 0.8849],
          [0.8553, 0.9965, 0.0086]],

         [[0.5029, 0.9746, 0.0415],
          [0.0170, 0.8830, 0.6042],
          [0.3107, 0.4233, 0.5056],
          ...,
          [0.4093, 0.5913, 0.1488],
          [0.3013, 0.0458, 0.1745],
          [0.5585, 0.5826, 0.4255]],

         [[0.7664, 0.0864, 0.6823],
          [0.1070, 0.9243, 0.7178],
          [0.7551, 0.0879, 0.9940],
          ...,
          [0.4047, 0.8336, 0.8355],
          [0.9248, 0.0975, 0.8620],
          [0.7967, 0.1466, 0.6437]],

         ...,

         [[0.4078, 0.4212, 0.2739],
          [0.0651, 0.9277, 0.8795],
          [0.0895, 0.6428, 0.4879],
          ...,
          [0.4958, 0.9991, 0.7008],
          [0.2199, 0.5013, 0.4774],
          [0.3578, 0.2593, 0.5101]],

         [[0.5881, 0.9346, 0.0239],
          [0.0192

In [4]:
import tensorflow as tf
images_tf = tf.zeros([32,28,28,3])
print(images_tf)

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
 