In [2]:
import numpy as np
import torch
import tensorflow as tf

In [5]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]

1

In [7]:
type(x[0])

numpy.int32

# Vector Transposition

In [8]:
xt = x.T
xt

array([1, 2, 3])

In [9]:
xt.shape

(3,)

In [15]:
yt = np.array([[25,66,6]])
yt.shape

(1, 3)

In [16]:
yt = yt.T
yt.shape

(3, 1)

In [19]:
# Zero Vectors
z = np.zeros(3)
z

array([0., 0., 0.])

In [23]:
# Vectors in  pytorch and tensorflow

xpt = torch.tensor([1,2,3])
print(xpt)

xtf = tf.Variable([1,2,3])
print(xtf)

tensor([1, 2, 3])
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>


# L2 Norms


In [ ]:
x 
print(np.linalg.norm(x)) 

3.7416573867739413


## L1 norm

In [9]:
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2])

6

## Squared L^2 Norm

In [10]:
np.dot(x,x)

14

## Max Norm

In [11]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

3

## Orthogonal Vectors

In [7]:
i = np.array([1,0])
i

array([1, 0])

In [8]:
j = np.array([0,1])
j


array([0, 1])

In [9]:
np.dot(i,j)

0

###  Matrices

In [14]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [15]:
X.size

6

In [16]:
X.shape

(3, 2)

In [17]:
X[1,0]

5

In [22]:
# select left column of matrix 
# r,c
X[:,0]

array([25,  5,  3])

In [19]:
# select left column of matrix x (zero indexed)
X[1,:]

array([ 5, 26])

In [24]:
# Another slicing by index example
print(X)
X[0:2,0:2]

[[25  2]
 [ 5 26]
 [ 3  7]]


array([[25,  2],
       [ 5, 26]])

### Matrices in Pytorch

In [28]:
xpt = torch.tensor([[25,5],[5,26],[3,7]])
xpt

tensor([[25,  5],
        [ 5, 26],
        [ 3,  7]])

In [29]:
xpt.shape

torch.Size([3, 2])

In [30]:
xpt[1,:]

tensor([ 5, 26])

###  Matrices in Tensorflow

In [33]:
xtf = tf.Variable([25,2],[5,26],[3,7])
xtf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([25,  2])>

In [34]:
tf.rank(xtf)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
tf.shape(xtf)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [40]:
print(xft)
xft[1,:]

tensor([[25,  5],
        [ 5, 26],
        [ 3,  7]])


tensor([ 5, 26])