In [4]:
import numpy as np
import torch
import tensorflow as tf

In [5]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]

1

In [7]:
type(x[0])

numpy.int32

# Vector Transposition

In [8]:
xt = x.T
xt

array([1, 2, 3])

In [9]:
xt.shape

(3,)

In [15]:
yt = np.array([[25,66,6]])
yt.shape

(1, 3)

In [16]:
yt = yt.T
yt.shape

(3, 1)

In [19]:
# Zero Vectors
z = np.zeros(3)
z

array([0., 0., 0.])

In [23]:
# Vectors in  pytorch and tensorflow

xpt = torch.tensor([1,2,3])
print(xpt)

xtf = tf.Variable([1,2,3])
print(xtf)

tensor([1, 2, 3])
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>


# L2 Norms


In [ ]:
x 
print(np.linalg.norm(x)) 

3.7416573867739413


## L1 norm

In [9]:
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2])

6

## Squared L^2 Norm

In [10]:
np.dot(x,x)

14

## Max Norm

In [11]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

3